### ISSUE TITLE
[Feature Request] Support for screen filters case scanlines (maybe shader support)

### ISSUE THREAD

**Issue by mrdeathjr28** [Arignir/Hades#26]
Hi

Maybe can add some option for filters case scanlines (maybe shader support)

thanks

**Comment by Arignir** [comment]
Hello,

I'm not sure to understand what you are requesting. Could you provide more explanations or even a screenshot/drawing?

Thank you for your support and for taking the time to check on my project ~

**Comment by mrdeathjr28** [comment]
> Hello,
> 
> I'm not sure to understand what you are requesting. Could you provide more explanations or even a screenshot/drawing?
> 
> Thank you for your support and for taking the time to check on my project ~

Maybe something like that

![197384317-39e40da0-0d0e-4898-8cda-3d81dee1ca34](https://user-images.githubusercontent.com/6601480/209891131-37db7b96-5d74-45f4-81a1-66faaa15f899.png)

thanks

**Comment by Arignir** [comment]
Fixed with https://github.com/Arignir/Hades/commit/1465ac625694e174156772332c12d52afbb42748, at least for the LCD effect.

<img width="742" alt="image" src="https://github.com/Arignir/Hades/assets/4798413/d1a06456-55d7-4307-a191-e65f2e8edda4">

It's a bit buggy if the window size is too small so I'd advise to have the display size set to at least 3 (`Video` -> `Display Size` -> `3`)
